# Generated by Django 2.2.2 on 2019-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
