# Generated by Django 2.2.2 on 2019-06-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_site', '0003_auto_20190624_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[('2', 'High'), ('1', 'Low')], default='1', max_length=1),
        ),
    ]
